kind: pipeline
name: cliente_deploy

steps:
  - name: nodejs-test
    image: node:12.6.0
    commands:
     - node --version
     - npm i
     - npm run build:test
    when:
      branch:
        - test
      event:
        - push
        - pull_request

  - name: nodejs-master
    image: node:12.6.0
    commands:
     - node --version
     - npm i
     - npm run build:prod
    when:
      branch:
      - master
      event:
      - push
      - pull_request

  - name: publish-s3-test
    image: plugins/s3
    settings:
      bucket: cliente-pruebas
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      region: us-east-1
      source: dist/**/*
      target: /pruebas${DRONE_REPO_NAME%%_cliente}.portaloas.udistrital.edu.co
      strip_prefix: dist/
    when:
      branch:
      - test
      event:
      - push
      - pull_request

  - name: publish-s3-master
    image: plugins/s3
    settings:
      bucket: cliente-prod
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      region: us-east-1
      source: dist/**/*
      target: /${DRONE_REPO_NAME%%_cliente}.portaloas.udistrital.edu.co
      strip_prefix: dist/
    when:
      branch:
      - master
      event:
      - push
      - pull_request

  - name: NotifyTelegram
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_to
    format: html
    message: >
      {{#success build.status}} With Drone 1.0
          <code>{{repo.owner}}/{{repo.name}}</code> <a href="{{build.link}}">SUCCESS</a>
          <code>{{commit.branch}}</code>@<a href="{{commit.link}}">{{truncate commit.sha 7}}</a><code> By:{{commit.author}}</code>
        {{else}}
          <code>{{repo.owner}}/{{repo.name}}</code> <a href="{{build.link}}">FAILURE</a>
          <code>{{commit.branch}}</code>@<a href="{{commit.link}}">{{truncate commit.sha 7}}</a><code> By:{{commit.author}}</code>
        {{/success}}
    when:
      branch:
      - master
      - test
      status:
      - failure
      - success
      event:
      - push
      - pull_request