export class ApiConstanst{
    public static INFO_COMPLEMENTARIA = { 
        TIPO_ETNIA: '1',
        TIPO_ESTADO_CIVIL: '2',
        TIPO_DISCAPACIDAD: '3',
        TIPO_ESTADOS: '4',
        INFO_SOCIOECONOMICA: '9',
        LOCALIDADES: '29',
        MUNICIPIOS: '30',
        ESTRATO: '31',
        DEPENDENCIA_ECONOMICA: '32',
        POSEE_SISBEN: '33',
        TIPO_COLEGIO: '34',
        TIPO_VIVIENDA: '36',
        CONVIVe_CON: '37',
        LUGAR_RES_FAM: '38',
        RES_MAT_DESEMPLEADO: '39',
        DESPLAZADO_POLITICO: '40',
        RES_FALLECIO: '41',
        RES_CABEZA_HOGAR: '42',
        DET_CAMBIO_ESTRATO: '43',
        DET_PERS_CARGO: '44',
        DET_DESPLAZADO: '45',
        INFO_COMPLEMENTARIA_SOLICITUD_RELIQUIDACION: '205',
    }

    public static SOLICITUDES = {
        ESTADO_SOLICITUD_RELIQUIDACION : '22',
        TIPO_SOLICITUD_RELIQUDIACION: '8',
    }

    public static TIPO_DOCUMENTO = {
        CERTIFICADO_DISCAPACIDAD: '26',
        CERTIFICADO_PENSION_ESCOLAR: '27',
        CERTIFICADO_ARRIENDO: '28',
        CERTIFICADO_HIPOTECA: '29',
        FORMULARIO_RELIQUIDACION: '30',
        CARTA_BIENESTAR: '31',
        CERTIFICADO_LUGAR_RES: '32',
        CERTIFICADO_SERVICIO_PUBLICO: '33',
        CERTIFICADO_INGRESOS: '34',
        CERTIFICADO_REG_CIVIL_HIJOS: '35',
        CERTIFICADO_DESPLAZADO: '36',
        CERTIFICADO_VALOR_MATRICULA: '37',
        CERTIFICADO_OTROS_DOCUMENTOS: '38',
    }
}