export class RolesConstanst{
    public static ROLES_SISTEMA = { 
        /* CONTRATISTA: "CONTRATISTA",
        SUPERVISOR: "SUPERVISOR",
        ADMIN_NECESIDADES: "ADMIN_NECESIDADES",
        ADMIN_PRESUPUESTO: "ADMIN_PRESUPUESTO",
        ADMIN_CONTABILIDAD: "ADMIN_CONTABILIDAD", */
        ADMIN_BIENESTAR: "ADMIN_BIENESTAR",
        ADMINISTRADOR_APOYO: "ADMINISTRADOR_APOYO",
        COORDINADOR_APOYO : "COORDINADOR_APOYO",
        ADMIN_CULTURA: "ADMIN_CULTURA",
        CULTURA: "CULTURA",
        lIDER_CULTURA: "LIDER_CULTURA",
        ESTUDIANTE: "ESTUDIANTE",
        ADMIN_TITAN: "ADMIN_TITAN"
    }
    public static ROLES_EMAIL = []
}
