export class RolesConstanst{
    public static ROLES_SISTEMA = { 
        CONTRATISTA: "CONTRATISTA",
        SUPERVISOR: "SUPERVISOR",
        ADMIN_NECESITADES: "ADMIN_NECESIDADES",
        ADMIN_PRESUPUESTO: "ADMIN_PRESUPUESTO",
        ADMIN_CONTABILIDAD: "ADMIN_CONTABILIDAD",
        ESTUDIANTE: "ESTUDIANTE",
    }
}