export class RolesConstanst{
    public static ROLES_SISTEMA = { 
        /* CONTRATISTA: "CONTRATISTA",
        SUPERVISOR: "SUPERVISOR",
        ADMIN_NECESIDADES: "ADMIN_NECESIDADES",
        ADMIN_PRESUPUESTO: "ADMIN_PRESUPUESTO",
        ADMIN_CONTABILIDAD: "ADMIN_CONTABILIDAD", */
        ADMIN_BIENESTAR: "ADMIN_BIENESTAR",
        ADMINISTRADOR_APOYO: "ADMINISTRADOR_APOYO",
        COORDINADOR_APOYO : "COORDINADOR_APOYO",
        ESTUDIANTE: "ESTUDIANTE",
        ADMINISTRADOR_DOCUMENTAL : "ADMINISTRADOR_DOCUMENTAL",
        FUNCIONARIO_DOCUMENTAL: "FUNCIONARIO_DOCUMENTAL",
        SUPERADMIN_DOCUMENTAL: "SUPERADMIN_DOCUMENTAL"
    }
    public static ROLES_EMAIL = []
}
